import Head from 'next/head';
import { useRouter } from 'next/router';
import React,{useState,useEffect} from 'react';
import { json } from 'stream/consumers';
import UiCome from '../../component/Ui/UiCome';
import UiHead from '../../component/Ui/UiHead';
import styles from "../../styles/Home.module.scss"
import UiTrending from '../../component/Ui/UiTrending';
import UiFooter from '../../component/Ui/UiFooter';
import UiListFilm from '../../component/Ui/UiListFilm';
import { APIGetIntro,APIGetIntroTheLoai,GetIntroTheLoaiProp } from '../../component/Func/APIGet';
import { Pagination } from 'antd';
import UiReload from '../../component/Ui/UiReload';

export interface ListPostProps {
  data_phim:any;
  total:any;
  pageNumber:any;
  data_wait:any;
}

export default function ListPost(props: ListPostProps) {
  const {data_phim,total,pageNumber,data_wait} = props
  const router = useRouter()
  const [check,setCheck] = useState(false)

  const GetIntro=async()=>{
    await setCheck(false)
    if(data_phim)
    {
      await setCheck(true)
    }
  }

  const onChange = async(pageNumber:any) => {
      window.open("/list/"+router.query.listID+"?page="+pageNumber,"_parent")
  };

  React.useEffect(()=>{
    if(!router.isReady) return;
    GetIntro()
  },[router.isReady])
  return (
    <div className={styles.main}>
      <Head>
        <title>Thể loại - {router.query.listID==='phim-le'?"Phim Lẻ":"Phim Bộ"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <UiHead />
        <div className='container'>
          <div className='row'>
            <div className='col-xl-9'>
              <UiListFilm data={data_phim} title={router.query.listID==='phim-le'?"Phim Lẻ":"Phim Bộ"} />
              <Pagination defaultCurrent={pageNumber} total={total} pageSize={24} className='m-3' onChange={onChange}/>
            </div>
            <div className='col-lg row'>
              <div className='col-md'>
                <UiCome title={"PHIM SẮP CHIẾU"} data={data_wait}/>
              </div>
              <div className='col-md'>
                <UiTrending title={"TRENDING"} />
              </div>
            </div>
          </div>
          <UiFooter />
        </div>
        {
        !check && <UiReload/>
        }
      </main>
      
    </div>
  );
}

export const getServerSideProps= async (context:any)=> { 
  let pageNumber:any = context.query?.page||1
  let param_wait:GetIntroTheLoaiProp={id_theloai:21,limit:8,offset:0}
  let ret_phim = await APIGetIntro({id_typephim:context.query.listID==='phim-le'?1:2,offset:(pageNumber-1)*24,limit:24})
  let ret_wait = await APIGetIntroTheLoai(param_wait)
  const data_wait= await ret_wait.data
  const total = await ret_phim.total_count
  const data_phim = await ret_phim.data
  return { props: { data_phim:data_phim,total:total,pageNumber:pageNumber,data_wait } }
}
