import Head from 'next/head';
import { useRouter } from 'next/router';
import * as React from 'react';
import { json } from 'stream/consumers';
import UiCome from '../../component/Ui/UiCome';
import UiHead from '../../component/Ui/UiHead';
import styles from "../../styles/Home.module.scss"
import UiTrending from '../../component/Ui/UiTrending';
import UiFooter from '../../component/Ui/UiFooter';
import UiHomeFilm from '../../component/Ui/UiHomeFilm';
import UiInfoFilm from '../../component/Ui/UiInfoFilm';
import {APIGetIntro,APIGetIntroLink} from "../../component/Func/APIGet"

export interface InfoIDPostProps {
  data:any
}

export interface IntroLinkProp
{
    link:any;
}
export interface DataLinkProp {
year:number;
director:string;
cast:string;
content:string;
link:string;
link_background:string;
name:string;
time:string;
country:string;
theloai:string;
}
export default function InfoIDPost(props: InfoIDPostProps) {
  const [data,setData] = React.useState([])
  const [datalink,setDataLink] = React.useState<DataLinkProp| any>();
  const [check,setCheck] = React.useState(false)
  const router = useRouter()  

  const GetIntro=async()=>{
    await setCheck(false)
    await setDataLink(props.data)
    let ret = await APIGetIntro()
    await setData(ret.data)
    await setCheck(true)

  }
  React.useEffect(()=>{
    if(!router.isReady) return;
    GetIntro()
  },[router.isReady])
  return (
    <div className={styles.main}>
      <Head>
        <title>InfoPost ID test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <UiHead />
        <div className='container'>
          <div className='row'>
            <div className='col-xl-9'>
              <UiInfoFilm ret_link={props.data}/>
              <UiHomeFilm title={"PHIM THỊNH HÀNH"} url="phim-thinh-hanh" data={data}/>
            </div>
            <div className='col-lg row'>
              <div className='col-md'>
                <UiCome title={"PHIM SẮP CHIẾU"} />
              </div>
              <div className='col-md'>
                <UiTrending title={"TRENDING"} />
              </div>
            </div>
          </div>
          <UiFooter />
        </div>
      </main>
    </div>
  );
}
export const getServerSideProps= async (context:any)=> { 
  let param_ep:IntroLinkProp={link: context.params.InfoID }
  let res = await APIGetIntroLink(param_ep)
  const data = await res.data
  return { props: { data } }
}
