import Head from 'next/head';
import { useRouter } from 'next/router';
import * as React from 'react';
import { json } from 'stream/consumers';
import UiCome from '../../component/Ui/UiCome';
import UiHead from '../../component/Ui/UiHead';
import styles from "../../styles/Home.module.scss"
import UiTrending from '../../component/Ui/UiTrending';
import UiFooter from '../../component/Ui/UiFooter';
import UiHomeFilm from '../../component/Ui/UiHomeFilm';
import UiInfoFilm from '../../component/Ui/UiInfoFilm';
import {APIGetIntro,APIGetIntroLink} from "../../component/Func/APIGet"

export interface InfoIDPostProps {
}

interface IntroLinkProp
{
    link:string;
}
interface DataLinkProp {
  director:string;
  cast: string;
  content: string;
  id: number;
  id_quocgia: number;
  id_theloai: number;
  id_typephim: number;
  link: string;
  link_background: string;
  name: string;
  time: string;
  year: number;
}
export default function InfoIDPost(props: InfoIDPostProps) {
  const [data,setData] = React.useState([])
  const [datalink,setDataLink] = React.useState<DataLinkProp>()
  const [check,setCheck] = React.useState(false)
  const router = useRouter()  

  const GetIntro=async()=>{
    await setCheck(false)
    let param:IntroLinkProp={link:router.query.InfoID}
    let ret_link = await APIGetIntroLink(param)
    await setDataLink(ret_link.data)
    let ret = await APIGetIntro()
    console.log(ret.data)
    await setData(ret.data)
    await setCheck(true)

  }
  React.useEffect(()=>{
    if(!router.isReady) return;
    GetIntro()
  },[router.isReady])
  return (
    <div className={styles.main}>
      <Head>
        <title>InfoPost ID test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <UiHead />
        <div className='container'>
          <div className='row'>
            <div className='col-xl-9'>
              {check && <UiInfoFilm title={"Hoán Hồn"} url="phim-thinh-hanh" ret_link={datalink}/>}
              <UiHomeFilm title={"PHIM THỊNH HÀNH"} url="phim-thinh-hanh" data={data}/>
            </div>
            <div className='col-lg row'>
              <div className='col-md'>
                <UiCome title={"PHIM SẮP CHIẾU"} />
              </div>
              <div className='col-md'>
                <UiTrending title={"TRENDING"} />
              </div>
            </div>
          </div>
          <UiFooter />
        </div>
      </main>
    </div>
  );
}
