import * as React from 'react';
import Head from 'next/head';
import UiHead from '../../component/Ui/UiHead';
export interface InfoPageProps {
}

export default function PostPage (props:InfoPageProps) {
  return (
    <div>
       <Head>
            <title>Danh sách phim</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <UiHead/>
          Danh sách phim
        </main>
    </div>
  );
}
