import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import UiHead from '../component/Ui/UiHead'
import styles from '../styles/Home.module.scss'
import UiCarousel from '../component/Ui/UiCarousel'
import UiHomeFilm from '../component/Ui/UiHomeFilm'
import UiFooter from '../component/Ui/UiFooter'
import UiCome from '../component/Ui/UiCome'
import UiTrending from '../component/Ui/UiTrending'
import UiReload from '../component/Ui/UiReload'
import {APIGetIntro,APIGetCarousel,APIGetIntroTheLoai,GetIntroProp,GetIntroTheLoaiProp} from "../component/Func/APIGet"
interface HomeProp
{
  data_phimle:any;
  data_phimbo:any;
  cinema:any;
  anime:any;
  data_carousel:any;
  data_wait:any;
}
const Home = (props:HomeProp) => {
  const {data_phimle,data_phimbo,cinema,anime,data_carousel,data_wait }=props
  const router = useRouter()
  const [playTime, setPlayTime] = useState(0);
  const [check,setCheck] = useState(false)
  const GetIntro=async()=>{
    await setCheck(false)
    
    await setCheck(true)
    
  }
  useEffect(()=>{
    GetIntro()
  },[])
  return (
    <div className={styles.main}>
      <Head>
        <title>Phim 24h - Kho phim tổng hợp hay nhất, mới nhất</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <link
          rel="stylesheet"
          href="https://video-react.github.io/assets/video-react.css"
        />
      </Head>
        {
          check && <main >
          <UiHead />
          <div className='container'>
            <UiCarousel  data={data_carousel}/>
            <div className='row'>
              <div className='col-xl-9'>
                <UiHomeFilm title={"PHIM LẺ MỚI CẬP NHẬT"} url="/list/phim-le" data={data_phimle}/>
                <UiHomeFilm title={"PHIM BỘ MỚI CẬP NHẬT"} url="/list/phim-bo" data={data_phimbo}/>
                <UiHomeFilm title={"PHIM ANIME - HOẠT HÌNH"} url="/genre/phim-anime" data={anime}/>
                <UiHomeFilm title={"PHIM CHIẾU RẠP"} url="/genre/phim-chieu-rap" data={cinema}/>
              </div>
              <div className='col-lg row'>
                <div className='col-md'>
                  <UiCome title={"PHIM SẮP CHIẾU"} data={data_wait}/>
                </div>
                <div className='col-md'>
                  <UiTrending title={"TRENDING"} />
                </div>
              </div>
            </div>
            <UiFooter/>
          </div>
        </main>
        }
        {
          !check && <div><UiReload/></div>
        }
    </div>
  )
}

export const getServerSideProps= async (context:any)=> { 
    let ret_carousel = await APIGetCarousel()
    let param_phimle:GetIntroProp={id_typephim:1,limit:8,offset:0}
    let param_phimbo:GetIntroProp={id_typephim:2,limit:8,offset:0}
    let param_cinema:GetIntroTheLoaiProp={id_theloai:9,limit:8,offset:0}
    let param_anime:GetIntroTheLoaiProp={id_theloai:20,limit:8,offset:0}
    let param_wait:GetIntroTheLoaiProp={id_theloai:21,limit:8,offset:0}

    let ret_phimle = await APIGetIntro(param_phimle)
    let ret_phimbo = await APIGetIntro(param_phimbo)
    let ret_cinema = await APIGetIntroTheLoai(param_cinema)
    let ret_anime = await APIGetIntroTheLoai(param_anime)
    let ret_wait = await APIGetIntroTheLoai(param_wait)
    const data_phimle = await ret_phimle.data
    const data_phimbo = await ret_phimbo.data
    const cinema = await ret_cinema.data
    const anime = await ret_anime.data
    const data_carousel= await ret_carousel.data
    const data_wait= await ret_wait.data
  return { props: { data_phimle,data_phimbo,cinema,anime,data_carousel,data_wait } }
}

export default Home
