import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import { Player } from 'video-react';
import UiHead from '../component/Ui/UiHead'
import styles from '../styles/Home.module.scss'
import UiCarousel from '../component/Ui/UiCarousel'
import UiHomeFilm from '../component/Ui/UiHomeFilm'
import UiFooter from '../component/Ui/UiFooter'
import UiCome from '../component/Ui/UiCome'
import UiTrending from '../component/Ui/UiTrending'
import {APIGetIntro} from "../component/Func/APIGet"
const Home: NextPage = () => {
  const router = useRouter()
  const [playTime, setPlayTime] = useState(0);
  const [data,setData] = useState([])
  const onClick = () => {
    router.push({
      pathname: "posts/[postID]",
      query: {
        postID: 123,
        ref: "soicical"
      }
    })
  }
  const GetIntro=async()=>{
    let ret = await APIGetIntro()
    console.log(ret.data)
    await setData(ret.data)
  }
  useEffect(()=>{
    GetIntro()
  },[])
  return (
    <div className={styles.main}>
      <Head>
        <title>Phim 24h - Kho phim tổng hợp hay nhất, mới nhất</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <link
          rel="stylesheet"
          href="https://video-react.github.io/assets/video-react.css"
        />
      </Head>

      <main >
        <UiHead />
        <div className='container'>
          <UiCarousel  data={data}/>
          <div className='row'>
            <div className='col-xl-9'>
              <UiHomeFilm title={"PHIM LẺ MỚI CẬP NHẬT"} url="phim-le" data={data}/>
              <UiHomeFilm title={"PHIM BỘ MỚI CẬP NHẬT"} url="phim-bo" data={data}/>
              <UiHomeFilm title={"PHIM CHIẾU RẠP"} url="phim-chieu-rap" data={data}/>
              <UiHomeFilm title={"PHIM THỊNH HÀNH"} url="phim-thinh-hanh" data={data}/>
            </div>
            <div className='col-lg row'>
              <div className='col-md'>
                <UiCome title={"PHIM SẮP CHIẾU"} />
              </div>
              <div className='col-md'>
                <UiTrending title={"TRENDING"} />
              </div>
            </div>
          </div>
          <UiFooter/>
        </div>
      </main>

    </div>
  )
}

export default Home
