import Head from 'next/head';
import { useRouter } from 'next/router';
import * as React from 'react';
import { json } from 'stream/consumers';
import UiCome from '../../component/Ui/UiCome';
import UiHead from '../../component/Ui/UiHead';
import styles from "../../styles/Home.module.scss"
import UiTrending from '../../component/Ui/UiTrending';
import UiFooter from '../../component/Ui/UiFooter';
import UiHomeFilm from '../../component/Ui/UiHomeFilm';
import UiInfoFilm from '../../component/Ui/UiInfoFilm';
export interface GenreIDPostProps {
}

export default function GenreIDPost(props: GenreIDPostProps) {
  const router = useRouter()
  console.log("InfoPost id :", JSON.stringify(router.query));

  return (
    <div className={styles.main}>
      <Head>
        <title>InfoPost ID test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <UiHead />
        <div className='container'>
          <div className='row'>
            <div className='col-xl-9'>
              <UiInfoFilm title={"Hoán Hồn"} url="phim-thinh-hanh" />
              <UiHomeFilm title={"PHIM THỊNH HÀNH"} url="phim-thinh-hanh" />
            </div>
            <div className='col-lg row'>
              <div className='col-md'>
                <UiCome title={"PHIM SẮP CHIẾU"} />
              </div>
              <div className='col-md'>
                <UiTrending title={"TRENDING"} />
              </div>
            </div>
          </div>
          <UiFooter />
        </div>
      </main>
    </div>
  );
}
