import Head from 'next/head';
import { useRouter } from 'next/router';
import React,{useState,useEffect} from 'react';
import { json } from 'stream/consumers';
import UiCome from '../../component/Ui/UiCome';
import UiHead from '../../component/Ui/UiHead';
import styles from "../../styles/Home.module.scss"
import UiTrending from '../../component/Ui/UiTrending';
import UiFooter from '../../component/Ui/UiFooter';
import UiListFilm from '../../component/Ui/UiListFilm';
import {APIGetIntroSearch,GetIntroSearchProp,GetIntroTheLoaiProp,APIGetIntroTheLoai } from '../../component/Func/APIGet';
import { Pagination } from 'antd';
import UiReload from '../../component/Ui/UiReload';

export interface SearchPostIDProps {
}

export default function SearchPostID(props: SearchPostIDProps) {
  const router = useRouter()
  const [check,setCheck] = useState(false)
    const [total,setToTal] = useState(0)
    const [data_phim,setDataPhim] = useState([])
    const [data_wait,setDataWait] = useState([])
    const [key,setKey] = useState("")
    const pageNumber:any = router.query.page

  const GetIntro=async()=>{
    await setCheck(false)
    let page:any=router.query.page;
    let param:GetIntroSearchProp={s_search:localStorage.getItem('key'),offset:(page?parseInt(page)-1:0)*24,limit:24}
    let param_wait:GetIntroTheLoaiProp={id_theloai:21,limit:8,offset:0}
    let ret_wait = await APIGetIntroTheLoai(param_wait)
    let ret_phim = await APIGetIntroSearch(param)

    await setToTal(await ret_phim.count_total)
    await setKey(await ret_phim.key)
    await setDataPhim( await ret_phim.data)
    console.log("s search",ret_phim.data)
    await setDataWait(await ret_wait.data)
    await setCheck(true)
  }
  const onChange = async(pageNumber:any) => {
      window.open("/search/key?page="+pageNumber,"_parent")
  };

  React.useEffect(()=>{
    if(!router.isReady) return;
    GetIntro()
  },[router.isReady])
  return (
    <div className={styles.main}>
      <Head>
        <title>Tìm kiếm phim - {key}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <UiHead />
        <div className='container'>
          <div className='row'>
            <div className='col-xl-9'>
              <UiListFilm data={data_phim} title={"Từ khóa tìm kiếm : "+key} />
              <Pagination defaultCurrent={pageNumber} total={total} pageSize={24} className='m-3' onChange={onChange}/>
            </div>
            <div className='col-lg row'>
              <div className='col-md'>
                <UiCome title={"PHIM SẮP CHIẾU"} data={data_wait}/>
              </div>
              <div className='col-md'>
                <UiTrending title={"TRENDING"} />
              </div>
            </div>
          </div>
          <UiFooter />
        </div>
        {
        !check && <UiReload/>
        }
      </main>
      
    </div>
  );
}