import * as React from 'react';
import Head from 'next/head';
import UiHead from '../../component/Ui/UiHead';
export interface WatchPageProps {
}

export default function WatchPage (props:WatchPageProps) {
  return (
    <div>
       <Head>
            <title>Xem phim</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <UiHead/>
        Xem phim
        </main>
    </div>
  );
}
