import Head from 'next/head';
import { useRouter } from 'next/router';
import React,{useState,useEffect} from 'react';
import { json } from 'stream/consumers';
import UiCome from '../../component/Ui/UiCome';
import UiHead from '../../component/Ui/UiHead';
import styles from "../../styles/Home.module.scss"
import UiTrending from '../../component/Ui/UiTrending';
import UiFooter from '../../component/Ui/UiFooter';
import UiListFilm from '../../component/Ui/UiListFilm';
import { APIGetIntroCountry,APIGetIntroTheLoai,GetIntroTheLoaiProp } from '../../component/Func/APIGet';
import { Pagination } from 'antd';
import UiReload from '../../component/Ui/UiReload';

export interface CountryPostProps {
  data_phim:any;
  total:any;
  title:any;
  pageNumber:any;
  data_wait:any;
}

export default function CountryPost(props: CountryPostProps) {
  const {data_phim,total,title,pageNumber,data_wait} = props
  const router = useRouter()
  const [check,setCheck] = useState(false)

  const GetIntro=async()=>{
    await setCheck(false)
    let ret_phim = await APIGetIntroCountry({link:router.query.countryID,offset:0*24,limit:24})
    console.log('APIGetIntroCountry',ret_phim)
    if(data_phim)
    {
      await setCheck(true)
    }
  }

  const onChange = async(page:any,pageSize:any) => {
      window.open("/country/"+router.query.countryID+"?page="+page,"_parent")
  };

  React.useEffect(()=>{
    if(!router.isReady) return;
    GetIntro()
  },[router.isReady])
  return (
    <div className={styles.main}>
      <Head>
        <title>Quốc gia - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <UiHead />
        <div className='container'>
          <div className='row'>
            <div className='col-xl-9'>
              <UiListFilm data={data_phim} title={"Quốc gia: "+title} />
              <Pagination defaultCurrent={pageNumber} total={total} pageSize={24} className='m-3' onChange={(page:any,pageSize:any)=>onChange(page,pageSize)}/>
            </div>
            <div className='col-lg row'>
              <div className='col-md'>
                <UiCome title={"PHIM SẮP CHIẾU"} data={data_wait}/>
              </div>
              <div className='col-md'>
                <UiTrending title={"TRENDING"} />
              </div>
            </div>
          </div>
          <UiFooter />
        </div>
        {
        !check && <UiReload/>
        }
      </main>
      
    </div>
  );
}

export const getServerSideProps= async (context:any)=> { 
  let param_wait:GetIntroTheLoaiProp={id_theloai:21,limit:8,offset:0}
  let ret_wait = await APIGetIntroTheLoai(param_wait)
  const data_wait= await ret_wait.data
  let pageNumber:any = context.query?.page||1
  let ret_phim = await APIGetIntroCountry({link:context.query.countryID,offset:(pageNumber-1)*24,limit:24})
     const total = await ret_phim.total_count
   const title = await ret_phim.title
   const data_phim = await ret_phim.data
   return { props: { data_phim:data_phim,total:total,title:title,pageNumber:pageNumber,data_wait } }
 }
